import { INestApplication } from '@nestjs/common';
import { AccountabilityService } from '../../src/accountability/accountability.service';
import { MaintenanceService } from '../../src/jobs/maintenance.service';
import { PrismaService } from '../../src/database/prisma.service';
import { todayIn, toDbDate, addDays } from '../../src/domain/dates';
import { createApp, registerUser, resetDb, threeCommitments } from './helpers';

const DAY = 24 * 60 * 60 * 1000;

/**
 * The MVP definition of done (spec §83), end to end against real Postgres:
 * register → goal → 3 commitments → occurrences → complete 2 + partial 1 → check-in →
 * score + streak → next day generated → adjust commitment → history unchanged → missed day handling.
 */
describe('Accountability loop (integration)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  beforeAll(async () => {
    app = await createApp();
    prisma = app.get(PrismaService);
    await resetDb(app);
  });
  afterAll(async () => app.close());

  it('runs the full daily loop', async () => {
    const { client, user } = await registerUser(app, { name: 'Loop User' });
    const today = todayIn(user.timezone);

    // Goal wizard: goal + 3 commitments + check-in time, activated.
    const created = await client.post('/goals', {
      title: 'Get a software engineering job',
      motivation: 'Career growth',
      successMeasure: 'Job offer received',
      category: 'CAREER',
      targetValue: 150,
      targetUnit: 'COUNT',
      progressCommitmentIndex: 0,
      checkInTime: '21:00',
      commitments: threeCommitments,
    });
    expect(created.status).toBe(201);
    const goal = created.body.data.goal;
    expect(goal).toMatchObject({ status: 'ACTIVE', isPrimary: true, commitmentCount: 3, progress: { type: 'NUMERIC', current: 0, target: 150 } });
    expect(created.body.data.warnings).toEqual([]);

    // Today's occurrences exist (generated by the wizard) — and lazy generation is idempotent.
    const tasks1 = await client.get('/tasks/today');
    const tasks2 = await client.get('/tasks/today');
    expect(tasks1.body.data.items).toHaveLength(3);
    expect(tasks2.body.data.items.map((t: { id: string }) => t.id).sort()).toEqual(tasks1.body.data.items.map((t: { id: string }) => t.id).sort());
    expect(await prisma.taskOccurrence.count({ where: { userId: user.id } })).toBe(3);

    const [apply, interview, read] = ['Apply to 5 jobs', 'Interview prep', 'Read docs'].map((t) =>
      tasks1.body.data.items.find((i: { title: string }) => i.title === t),
    );

    // Complete 2, partially complete 1.
    const c1 = await client.post(`/task-occurrences/${apply.id}/complete`);
    expect(c1.body.data.occurrence).toMatchObject({ status: 'COMPLETED', actualValue: 5, completionPercentage: 100 });
    await client.post(`/task-occurrences/${read.id}/complete`);
    const p = await client.post(`/task-occurrences/${interview.id}/partial`, { actualValue: 20 });
    expect(p.body.data.occurrence).toMatchObject({ status: 'PARTIAL', completionPercentage: 66 });
    expect(p.body.data.day).toMatchObject({ completionPercentage: 89, completedCount: 2, plannedCount: 3 });

    // Invalid transitions are rejected with stable codes.
    expect((await client.post(`/task-occurrences/${interview.id}/partial`, { actualValue: 45 })).body.error.code).toBe('INVALID_PARTIAL');
    expect((await client.post(`/task-occurrences/${read.id}/partial`, { actualValue: 0.5 })).body.error.code).toBe('INVALID_PARTIAL');

    // Check-ins and completions are separate: no streak yet without a check-in.
    let dash = await client.get('/dashboard');
    expect(dash.body.data.today).toMatchObject({ completionPercentage: 89, completedCount: 2, remainingCount: 0 });
    expect(dash.body.data.today.checkIn.status).toBe('PENDING');
    expect(dash.body.data.streak.current).toBe(0);
    expect(dash.body.data.nextAction.type).toBe('CHECK_IN');

    // Submit check-in (step 1 statuses, blockers, confidence, reflection).
    const ci = await client.post('/checkins', {
      items: [
        { occurrenceId: apply.id, status: 'COMPLETED' },
        { occurrenceId: interview.id, status: 'PARTIAL', actualValue: 20 },
        { occurrenceId: read.id, status: 'COMPLETED' },
      ],
      blockers: ['UNEXPECTED_WORK'],
      blockerNote: 'Work ran late',
      confidence: 4,
      reflection: 'Applications done early.',
    });
    expect(ci.status).toBe(201);
    expect(ci.body.data.checkIn).toMatchObject({ status: 'COMPLETED', confidence: 4, blockers: ['UNEXPECTED_WORK'], completionPercentage: 89 });
    expect(ci.body.data.day).toMatchObject({ isSuccessful: true, completionPercentage: 89 });
    expect(ci.body.data.day.dailyScore).toBe(Math.round((89 * 0.5 + 100 * 0.2 + 67 * 0.2) / 0.9));
    expect(ci.body.data.streak.current).toBe(1);
    expect(ci.body.data.feedback.headline).toBeTruthy();

    // One check-in per user per date: resubmitting updates the same row.
    await client.post('/checkins', { items: [], confidence: 5 });
    expect(await prisma.checkIn.count({ where: { userId: user.id } })).toBe(1);

    dash = await client.get('/dashboard');
    expect(dash.body.data.streak).toMatchObject({ current: 1, longest: 1 });
    expect(dash.body.data.goal.progress).toMatchObject({ current: 5, percentage: 3 });
    expect(dash.body.data.nextAction.type).toBe('DONE');

    // Adjust a commitment (5 → 3 applications). Today's touched occurrence keeps its snapshot.
    const commitmentId = apply.commitmentId;
    const edit = await client.patch(`/commitments/${commitmentId}`, { targetValue: 3, title: 'Apply to 3 jobs' });
    expect(edit.status).toBe(200);
    const todayApply = await prisma.taskOccurrence.findUniqueOrThrow({ where: { id: apply.id } });
    expect(Number(todayApply.targetValue)).toBe(5);
    expect(todayApply.title).toBe('Apply to 5 jobs');

    // Next day: the job generates new occurrences using the new settings; history is unchanged.
    const maintenance = app.get(MaintenanceService);
    const tomorrowNow = new Date(Date.now() + DAY);
    await maintenance.runForUser(user.id, tomorrowNow);
    const tomorrow = addDays(today, 1);
    const next = await prisma.taskOccurrence.findMany({ where: { userId: user.id, scheduledDate: toDbDate(tomorrow) } });
    expect(next).toHaveLength(3);
    const nextApply = next.find((o) => o.taskId === apply.taskId)!;
    expect(Number(nextApply.targetValue)).toBe(3);
    expect(nextApply.title).toBe('Apply to 3 jobs');
    expect(Number((await prisma.taskOccurrence.findUniqueOrThrow({ where: { id: apply.id } })).targetValue)).toBe(5);

    // Yesterday (the real today) is now final and unchanged.
    const day1 = await prisma.dailyAccountability.findUniqueOrThrow({ where: { userId_date: { userId: user.id, date: toDbDate(today) } } });
    expect(day1).toMatchObject({ isFinal: true, isSuccessful: true, completionPercentage: 89, streakDay: 1 });

    // Running the job again is a no-op (idempotent).
    await maintenance.runForUser(user.id, tomorrowNow);
    expect(await prisma.taskOccurrence.count({ where: { userId: user.id } })).toBe(6);

    // Day after: tomorrow was never checked in → tasks MISSED, check-in MISSED, kind notification, streak resets.
    await app.get(AccountabilityService).catchUp(user.id, new Date(Date.now() + 2 * DAY));
    const missedDay = await prisma.dailyAccountability.findUniqueOrThrow({ where: { userId_date: { userId: user.id, date: toDbDate(tomorrow) } } });
    expect(missedDay).toMatchObject({ isFinal: true, isSuccessful: false, checkInCompleted: false, completionPercentage: 0, missedCount: 3 });
    const ciTomorrow = await prisma.checkIn.findUniqueOrThrow({ where: { userId_date: { userId: user.id, date: toDbDate(tomorrow) } } });
    expect(ciTomorrow.status).toBe('MISSED');
    const notes = await prisma.notification.findMany({ where: { userId: user.id, type: 'CHECKIN_MISSED' } });
    expect(notes).toHaveLength(1);
    expect(notes[0].body).toMatch(/No problem/);
    const streak = await prisma.streak.findUniqueOrThrow({ where: { userId: user.id } });
    expect(streak).toMatchObject({ currentStreak: 0, longestStreak: 1, previousStreak: 1 });

    // Audit trail captured the important mutations.
    const actions = (await prisma.auditLog.findMany({ where: { userId: user.id } })).map((a) => a.action);
    expect(actions).toEqual(expect.arrayContaining(['GOAL_CREATED', 'COMMITMENT_CREATED', 'TASK_COMPLETED', 'TASK_CHANGED', 'CHECKIN_SUBMITTED', 'COMMITMENT_CHANGED']));
  });

  it('closes a day only after its scheduled end (never early)', async () => {
    const { client, user } = await registerUser(app);
    await client.post('/goals', { title: 'Fitness', category: 'FITNESS', commitments: [threeCommitments[2]] });
    const acc = app.get(AccountabilityService);
    const u = await acc.loadUser(prisma, user.id);
    const today = todayIn(u.timezone);
    await acc.closeDay(prisma, u, today, new Date()); // mid-day: must be a no-op
    const occ = await prisma.taskOccurrence.findFirstOrThrow({ where: { userId: user.id } });
    expect(occ.status).toBe('PENDING');
    expect((await prisma.checkIn.findFirstOrThrow({ where: { userId: user.id } })).status).toBe('PENDING');
  });

  it('supports flexible N-times-per-week commitments', async () => {
    const { client } = await registerUser(app);
    await client.post('/goals', {
      title: 'Get fit',
      category: 'FITNESS',
      commitments: [{ title: 'Workout', recurrence: { type: 'TIMES_PER_WEEK', timesPerWeek: 4 }, targetValue: 1, targetUnit: 'BOOLEAN' }],
    });
    const items = (await client.get('/tasks/today')).body.data.items;
    expect(items).toHaveLength(1);
    expect(items[0]).toMatchObject({ period: 'WEEK', targetValue: 4, targetUnit: 'COUNT', status: 'PENDING' });
    const one = await client.patch(`/task-occurrences/${items[0].id}`, { actualValue: 1 });
    expect(one.body.data.occurrence).toMatchObject({ status: 'IN_PROGRESS', completionPercentage: 25 });
    const four = await client.patch(`/task-occurrences/${items[0].id}`, { actualValue: 4 });
    expect(four.body.data.occurrence).toMatchObject({ status: 'COMPLETED', completionPercentage: 100 });
    // Weekly counts don't distort the daily score.
    expect(four.body.data.day.plannedCount).toBe(0);
  });

  it('respects rest days: nothing is generated and the streak is not broken', async () => {
    const { client, user } = await registerUser(app);
    const acc = app.get(AccountabilityService);
    const u0 = await acc.loadUser(prisma, user.id);
    const iso = ((new Date(`${todayIn(u0.timezone)}T12:00:00Z`).getUTCDay() + 6) % 7) + 1;
    await client.patch('/users/me', { restDays: [iso] });
    await client.post('/goals', { title: 'Study', category: 'STUDY', commitments: [threeCommitments[1]] });
    const dash = await client.get('/dashboard');
    expect(dash.body.data.today).toMatchObject({ isRestDay: true, plannedCount: 0 });
    expect(dash.body.data.nextAction.type).toBe('REST');
  });

  it('pausing a commitment skips today (history kept) and resuming restores it', async () => {
    const { client } = await registerUser(app);
    const g = await client.post('/goals', { title: 'Learn', category: 'STUDY', commitments: [threeCommitments[1], threeCommitments[2]] });
    const cid = g.body.data.goal.commitments[0].id;
    expect((await client.post(`/commitments/${cid}/pause`)).body.data.status).toBe('PAUSED');
    let items = (await client.get('/tasks/today')).body.data.items;
    expect(items.find((i: { commitmentId: string }) => i.commitmentId === cid).status).toBe('SKIPPED');
    expect((await client.get('/dashboard')).body.data.today.plannedCount).toBe(1);
    expect((await client.post(`/commitments/${cid}/resume`)).body.data.status).toBe('ACTIVE');
    items = (await client.get('/tasks/today')).body.data.items;
    expect(items.find((i: { commitmentId: string }) => i.commitmentId === cid).status).toBe('PENDING');
  });

  it('enforces goal rules: explicit completion, read-only when completed, archive instead of delete', async () => {
    const { client } = await registerUser(app);
    const g = (await client.post('/goals', { title: 'Ship side project', category: 'CODING', commitments: [threeCommitments[2]] })).body.data.goal;
    const occ = (await client.get('/tasks/today')).body.data.items[0];
    await client.post(`/task-occurrences/${occ.id}/complete`);

    expect((await client.post(`/goals/${g.id}/complete`, {})).body.error.code).toBe('VALIDATION_ERROR');
    const done = await client.post(`/goals/${g.id}/complete`, { confirm: true, notes: 'Shipped v1' });
    expect(done.body.data).toMatchObject({ status: 'COMPLETED', readOnly: true });
    expect((await client.patch(`/goals/${g.id}`, { title: 'New' })).body.error.code).toBe('GOAL_READ_ONLY');
    expect((await client.patch(`/goals/${g.id}`, { notes: 'Retro: keep scope small' })).status).toBe(200);
    expect((await client.post(`/goals/${g.id}/commitments`, threeCommitments[0])).body.error.code).toBe('GOAL_READ_ONLY');

    // Goal with history → abandoned (kept), goal without history → deleted.
    const g2 = (await client.post('/goals', { title: 'Second', category: 'OTHER', commitments: [threeCommitments[2]] })).body.data.goal;
    const o2 = (await client.get('/tasks/today')).body.data.items.find((i: { goalId: string }) => i.goalId === g2.id);
    await client.post(`/task-occurrences/${o2.id}/miss`);
    expect((await client.delete(`/goals/${g2.id}`)).body.data).toMatchObject({ abandoned: true, deleted: false });
    const g3 = (await client.post('/goals', { title: 'Draft', category: 'OTHER', activate: false })).body.data.goal;
    expect(g3.status).toBe('DRAFT');
    expect((await client.delete(`/goals/${g3.id}`)).body.data).toMatchObject({ deleted: true });
  });

  it('applies free-plan limits and plan warnings (guide, don’t block)', async () => {
    const { client } = await registerUser(app);
    const heavy = await client.post('/goals', {
      title: 'Marathon prep',
      category: 'FITNESS',
      commitments: [
        { title: 'Run', recurrence: { type: 'DAILY' }, targetValue: 4, targetUnit: 'HOURS' },
        { title: 'Study', recurrence: { type: 'DAILY' }, targetValue: 4, targetUnit: 'HOURS' },
      ],
    });
    expect(heavy.status).toBe(201);
    expect(heavy.body.data.warnings[0]).toMatch(/hours a day/);
    const second = await client.post('/goals', { title: 'Another', category: 'OTHER' });
    expect(second.status).toBe(403);
    expect(second.body.error.code).toBe('PLAN_LIMIT_REACHED');
  });
});
